services:
  - type: web
    name: chosen-generation-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: MPESA_AMOUNT
        value: "20"
      - key: MPESA_ENV
        value: "sandbox"
